name: Label auto-merge PRs

on:
  pull_request:
    tags: automerge
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Show a message
        run: echo "Mergeou com sucesso!!"
