name: matrix
on: [push]
jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Show a message
        run: echo ${{ matrix.version }}